<?php

namespace App\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-30 at 23:34:46.
 */
class PageTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Page
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Page;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

}
