<?php

namespace App\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-30 at 23:34:00.
 */
class MenuItemTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var MenuItem
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new MenuItem;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers App\Model\MenuItem::getRoot
	 * @todo   Implement testGetRoot().
	 */
	public function testGetRoot() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers App\Model\MenuItem::getPath
	 * @todo   Implement testGetPath().
	 */
	public function testGetPath() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers App\Model\MenuItem::hasChildren
	 * @todo   Implement testHasChildren().
	 */
	public function testHasChildren() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers App\Model\MenuItem::getChildren
	 * @todo   Implement testGetChildren().
	 */
	public function testGetChildren() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
