<?php

namespace App\Helper;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-13 at 23:20:04.
 */
class XMLHelperTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var XMLHelper
	 */
	protected $object;
	
	protected $data = '<?xml version="1.0" encoding="utf-8"?>
						<page version="1.0" tpl="3-col">
						   <head><widget id="1"/></head>
						   <content>
							   <control type="blogpostslist" container="col-left" config="last"/>
							   <document id="1" container="col-center"/>
						   </content>
						</page>';

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$doc = new \DOMDocument;
		$doc->loadXML($this->data);
		$this->object = $doc->getElementsByTagName('page')[0];
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers App\Helper\XMLHelper::xml_to_std
	 */
	public function testXml_to_std() {
		$ret = XMLHelper::xml_to_std($this->object);
		$this->assertObjectHasAttribute('name', $ret);
		$this->assertTrue($ret->name == 'page');
	}
	/**
	 * @covers App\Helper\XMLHelper::xml_to_std with $filter
	 */
	public function testFilterXml_to_std() {
		$ret = XMLHelper::xml_to_std($this->object, [XML_TEXT_NODE , XML_COMMENT_NODE]);
		$this->assertNotNull($ret);
		$this->assertTrue(isset($ret->name) && $ret->name == 'page');
	}

	/**
	 * @covers App\Helper\XMLHelper::xml_to_array
	 * @todo   Implement testXml_to_array().
	 */
	public function testXml_to_array() {
		$ret = XMLHelper::xml_to_array($this->object);
		$this->assertArrayHasKey('head', $ret);
		$this->assertArrayHasKey('content', $ret);
	}

}
