<?php

namespace App\Model\Catalog;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-31 at 00:58:23.
 */
class CategoryTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Category
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Category;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers App\Model\Catalog\Category::__get
	 * @todo   Implement test__get().
	 */
	public function test__get() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers App\Model\Catalog\Category::hasChildren
	 * @todo   Implement testHasChildren().
	 */
	public function testHasChildren() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers App\Model\Catalog\Category::getChildren
	 * @todo   Implement testGetChildren().
	 */
	public function testGetChildren() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers App\Model\Catalog\Category::getAttribute
	 * @todo   Implement testGetAttribute().
	 */
	public function testGetAttribute() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
