<?php

namespace App\Model\Security;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-31 at 00:01:46.
 */
class UserGroupTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var UserGroup
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new UserGroup;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

}
