<?php

namespace App\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-31 at 00:01:45.
 */
class UserTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var User
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new User;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers App\Model\User::getName
	 * @todo   Implement testGetName().
	 */
	public function testGetName() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers App\Model\User::getGroups
	 * @todo   Implement testGetGroups().
	 */
	public function testGetGroups() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers App\Model\User::getData
	 * @todo   Implement testGetData().
	 */
	public function testGetData() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
