<?php

namespace App\Model;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-17 at 12:02:14.
 */
class UserManagerTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var UserManager
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Security\UserManager;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers App\Model\UserManager::authenticate
	 * @todo   Implement testAuthenticate().
	 */
	public function testAuthenticate() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers App\Model\UserManager::add
	 * @todo   Implement testAdd().
	 */
	public function testAdd() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers App\Model\UserManager::getList
	 * @todo   Implement testGetList().
	 */
	public function testGetList() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers App\Model\UserManager::isAllowed
	 * @todo   Implement testIsAllowed().
	 */
	public function testIsAllowed() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
