<?php

namespace App\Model\Catalog;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-08 at 12:20:40.
 */
class ProductTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Product
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = Product::get(1);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers App\Model\Catalog\Product::getAttributes
	 * @todo   Implement testGetAttributes().
	 */
	public function testGetAttributes() {
		$this->assertNotNull($this->object->getAttributes());
		$this->assertGreaterThan(5, $this->object->getAttributes()->count());
	}

}
