<?php
namespace App\Model\Catalog;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-24 at 10:20:29.
 */
class ProductAttributeCollectionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ProductAttributeCollection
     */
    protected $object;
    protected $product;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ProductAttributeCollection;
		$this->product = Product::get(1);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
	
	/**
	 * @covers App\Model\Catalog\ProductAttributeCollection::setProduct($product)
	 */
	public function testSetProduct() {
		$this->object->setProduct($this->product);
		$this->assertNotEmpty($this->object->getProduct());
		$this->assertEquals($this->product, $this->object->getProduct());
	}
	/**
	 * @covers App\Model\Catalog\ProductAttributeCollection
	 * @todo   Implement tests.
	 */
	public function testGetIt() {
		$this->object->setProduct($this->product);
		$this->assertNotEmpty($this->object);
		$this->assertGreaterThan(0, $this->object->findAll()->count());
	}
}
